name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: build and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: ${{ secrets.SCRIPTS }}
